GET http://localhost:3001/api/superadmins/all
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG5hbWUiOiJiZW5qYW1pbkBnbWFpbC5jb20iLCJhZHBhc3N3b3JkIjoiYXplciIsImlhdCI6MTYxNzMxMTcwNH0.hLvaSN8f6dwZeM1G27S2JwyffjORlpj0diodqbuMjUQ
###
POST http://localhost:3001/api/superadmins/add
Content-Type: application/json

{
    "fullname" : "naoufal",
    "email" : "test@gmail.com",
    "password" : "azer"
}

###
POST http://localhost:3001/api/superadmins/auth
Content-Type: application/json

{
    "email" : "benjamin@gmail.com",
    "password" : "azer"
}

###

POST http://localhost:3001/api/admins/add
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG5hbWUiOiJiZW5qYW1pbkBnbWFpbC5jb20iLCJhZHBhc3N3b3JkIjoiYXplciIsImlhdCI6MTYxNTg0ODg0OH0.ARuPIMs05CBOGgtJBcgzIYlf0T7Zce_v49hWKgnUpe4

{
    "fullname" : "naoufal",
    "email" : "mare32980@gmail.com",
    "phone" : 614675855,
    "password" : "azer",
    "is_reseted" : false,
    "stat" : false
}

###

GET http://localhost:3001/api/admins/all
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG5hbWUiOiJiZW5qYW1pbkBnbWFpbC5jb20iLCJhZHBhc3N3b3JkIjoiYXplciIsImlhdCI6MTYxNTg0ODg0OH0.ARuPIMs05CBOGgtJBcgzIYlf0T7Zce_v49hWKgnUpe4

###

PATCH http://localhost:3001/api/admins/edit/6051179c422fce237c792597
Content-Type: application/json

{
    "password" : "test test"
}

###

DELETE http://localhost:3001/api/admins/delete/605360841aec771064e4fbab

###

GET http://localhost:3001/api/admins/allAdmins

###

POST http://localhost:3001/api/admins/authAdmin
Content-Type: application/json

{
    "email" : "naoufelbenmensour@gmail.com",
    "password" : "azer"
}

###
GET http://localhost:3001/api/productsType/all

###

DELETE http://localhost:3001/api/productsTpe/delete/60577f06e84cb35eb02e4c80

###

GET http://localhost:3001/api/users/allBuyers

###

GET http://localhost:3001/api/users/allSellers

###

POST http://localhost:3001/api/users/add
Content-Type: application/json

{
    "fullname" : "test2",
    "email" : "test2@gmail.com",
    "phone" : 614675855,
    "role" : "buyer",
    "is_reseted" : false,
    "password" : "azer"
}

###

GET http://localhost:3001/api/delivery/all

###

POST http://localhost:3001/api/delivery/add
Content-Type : application/json

{
    "fullname" : "delivery 2",
    "email" : "delivery2@gmail.com",
    "phone" : 614675855,
    "stat" : "available"
}

###

GET http://localhost:3001/api/pricing/all

###

POST http://localhost:3001/api/pricing/add
Content-Type: application/json

{
    "name" : "Expert Pack",
    "score" : 5000,
    "desc" : "This is an Expert Pack, You can sell infinite products Express Delivery"
}

###

GET http://localhost:3001/api/products/allBySeller/6064507e6de79722e8c2acf8

###

GET http://localhost:3001/api/products/oneProduct/6065e850ac73a8428c1312bb

###

GET http://localhost:3001/api/products/all

###
GET http://localhost:3001/api/ads/all 

###

GET http://localhost:3001/api/commands/all

###

POST http://localhost:3001/api/commands/add
Content-Type: application/json

{
    "productName" : "productName",
    "buyerEmail" : "buyerEmail",
    "idSeller" : "idSeller",
    "price" : 12000,
    "date" : "Sun Apr 04 2021 18:37:22 GMT+0100 (UTC+01:00)",
    "is_validate" : false
}

###

GET http://localhost:3001/api/commands/allBySeller/6064507e6de79722e8c2acf8