GET http://localhost:3001/api/superadmins/all
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG5hbWUiOiJ0ZXN0QGdtYWlsLmNvbSIsImFkcGFzc3dvcmQiOiJhemVyIiwiaWF0IjoxNjE1ODMyNjQwfQ.nLvoaGsrEwSH0hd-rz204d2qU9k2ib1GqVAy6nXi3Xw
###
POST http://localhost:3001/api/superadmins/add
Content-Type: application/json

{
    "fullname" : "naoufal",
    "email" : "test@gmail.com",
    "password" : "azer"
}

###
POST http://localhost:3001/api/superadmins/auth
Content-Type: application/json

{
    "email" : "benjamin@gmail.com",
    "password" : "azer"
}

###

POST http://localhost:3001/api/admins/add
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG5hbWUiOiJiZW5qYW1pbkBnbWFpbC5jb20iLCJhZHBhc3N3b3JkIjoiYXplciIsImlhdCI6MTYxNTgzODg1NH0.rxibXazYkh_f-2iHG4oF4MZJFADaTZvsvGlR-AVhHog

{
    "fullname" : "naoufal",
    "email" : "test@gmail.com",
    "phone" : 614675855,
    "password" : "azer"
}

###

GET http://localhost:3001/api/admins/all